"""empty message

Revision ID: 01316a340a60
Revises: d7516a808aa6
Create Date: 2026-09-15 19:57:39.426903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01316a340a60'
down_revision: Union[str, Sequence[str], None] = 'd7516a808aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_analyst_id'), 'alerts', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analysts_organization_id'), 'analysts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_activity_asset_id'), 'asset_activity', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investigations_alert_id'), 'investigations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_investigations_analyst_id'), 'investigations', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_peer_benchmarks_organization_id'), 'peer_benchmarks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_benchmarks_organization_id'), table_name='peer_benchmarks')
    op.drop_index(op.f('ix_investigations_analyst_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_alert_id'), table_name='investigations')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_asset_activity_asset_id'), table_name='asset_activity')
    op.drop_index(op.f('ix_analysts_organization_id'), table_name='analysts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_analyst_id'), table_name='alerts')
    # ### end Alembic commands ###
