"""create core SAT-SA models

Revision ID: 78e6b17544da
Revises: 
Create Date: 2026-09-09 18:29:12.506530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e6b17544da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_external_id'), 'incidents', ['external_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('analysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysts_organization_id'), 'analysts', ['organization_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_identifier'), 'assets', ['asset_identifier'], unique=True)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_table('peer_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('peer_mean', sa.Float(), nullable=False),
    sa.Column('peer_stddev', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_benchmarks_organization_id'), 'peer_benchmarks', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('closure_time_minutes', sa.Integer(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('escalation', sa.Boolean(), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['analysts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_analyst_id'), 'alerts', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_external_id'), 'alerts', ['external_id'], unique=True)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('asset_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_activity_asset_id'), 'asset_activity', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_activity_timestamp'), 'asset_activity', ['timestamp'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actions_performed', sa.Text(), nullable=True),
    sa.Column('evidence_reviewed', sa.Text(), nullable=True),
    sa.Column('queries_executed', sa.Text(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('escalation_decision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_alert_id'), 'investigations', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_alert_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_asset_activity_timestamp'), table_name='asset_activity')
    op.drop_index(op.f('ix_asset_activity_asset_id'), table_name='asset_activity')
    op.drop_table('asset_activity')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_external_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_analyst_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_peer_benchmarks_organization_id'), table_name='peer_benchmarks')
    op.drop_table('peer_benchmarks')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_identifier'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_analysts_organization_id'), table_name='analysts')
    op.drop_table('analysts')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_incidents_external_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
