"""align models with CSV schemas

Revision ID: d7516a808aa6
Revises: 78e6b17544da
Create Date: 2026-09-11
"""

from alembic import op
import sqlalchemy as sa


revision = "d7516a808aa6"
down_revision = "78e6b17544da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop old development tables.
    # The database is still empty, so recreating the schema is safe.

    op.drop_table("investigations")
    op.drop_table("alerts")
    op.drop_table("asset_activity")
    op.drop_table("peer_benchmarks")
    op.drop_table("incidents")
    op.drop_table("assets")
    op.drop_table("analysts")
    op.drop_table("organizations")

    # Organizations
    op.create_table(
        "organizations",
        sa.Column(
            "organization_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "organization_name",
            sa.String(length=150),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "industry",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "organization_size",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "soc_maturity",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "region",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.Date(),
            nullable=True,
        ),
    )

    # Analysts
    op.create_table(
        "analysts",
        sa.Column(
            "analyst_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "organization_id",
            sa.String(length=20),
            sa.ForeignKey("organizations.organization_id"),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "team",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "experience_years",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "shift",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "joined_at",
            sa.Date(),
            nullable=True,
        ),
    )

    # Assets
    op.create_table(
        "assets",
        sa.Column(
            "asset_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "organization_id",
            sa.String(length=20),
            sa.ForeignKey("organizations.organization_id"),
            nullable=False,
        ),
        sa.Column(
            "asset_identifier",
            sa.String(length=100),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "asset_name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "asset_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "criticality",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "environment",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "location",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
    )

    # Incidents
    op.create_table(
        "incidents",
        sa.Column(
            "incident_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "external_id",
            sa.String(length=100),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "organization_id",
            sa.String(length=20),
            sa.ForeignKey("organizations.organization_id"),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    # Alerts
    op.create_table(
        "alerts",
        sa.Column(
            "alert_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "external_id",
            sa.String(length=100),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "organization_id",
            sa.String(length=20),
            sa.ForeignKey("organizations.organization_id"),
            nullable=False,
        ),
        sa.Column(
            "asset_id",
            sa.String(length=20),
            sa.ForeignKey("assets.asset_id"),
            nullable=False,
        ),
        sa.Column(
            "analyst_id",
            sa.String(length=20),
            sa.ForeignKey("analysts.analyst_id"),
            nullable=True,
        ),
        sa.Column(
            "alert_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "closed_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "closure_time_minutes",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "investigation_notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "evidence_reviewed",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "escalated",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "false_positive",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "incident_id",
            sa.String(length=20),
            sa.ForeignKey("incidents.incident_id"),
            nullable=True,
        ),
    )

    # Investigations
    op.create_table(
        "investigations",
        sa.Column(
            "investigation_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "alert_id",
            sa.String(length=20),
            sa.ForeignKey("alerts.alert_id"),
            nullable=False,
        ),
        sa.Column(
            "analyst_id",
            sa.String(length=20),
            sa.ForeignKey("analysts.analyst_id"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "duration_minutes",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "actions_performed",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "queries_executed",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "evidence_reviewed",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "investigation_notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "findings",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "escalation_decision",
            sa.Boolean(),
            nullable=True,
        ),
    )

    # Asset activity
    op.create_table(
        "asset_activity",
        sa.Column(
            "activity_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "asset_id",
            sa.String(length=20),
            sa.ForeignKey("assets.asset_id"),
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "event_count",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "log_sources_active",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "network_events",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "authentication_events",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
    )

    # Peer benchmarks
    op.create_table(
        "peer_benchmarks",
        sa.Column(
            "benchmark_id",
            sa.String(length=20),
            primary_key=True,
        ),
        sa.Column(
            "organization_id",
            sa.String(length=20),
            sa.ForeignKey("organizations.organization_id"),
            nullable=False,
        ),
        sa.Column(
            "metric_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "metric_value",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "peer_mean",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "peer_stddev",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "benchmark_period",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "calculated_at",
            sa.DateTime(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_table("investigations")
    op.drop_table("alerts")
    op.drop_table("asset_activity")
    op.drop_table("peer_benchmarks")
    op.drop_table("incidents")
    op.drop_table("assets")
    op.drop_table("analysts")
    op.drop_table("organizations")